# Generated by Django 4.2.4 on 2023-08-07 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_loanfund'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanfund',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='loanfund',
            name='loan_duration',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='loanfund',
            name='max_loan_amount',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanfund',
            name='min_loan_amount',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
            preserve_default=False,
        ),
    ]
