# Generated by Django 4.2.4 on 2023-08-07 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_loan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='loan_fund_ID',
            new_name='loan_fund_Name',
        ),
    ]
