# Generated by Django 4.2.4 on 2023-08-07 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_rename_loan_fund_id_loan_loan_fund_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='loan_fund_Name',
            new_name='loan_fund_ID',
        ),
    ]
