# Generated by Django 4.2.4 on 2023-09-07 12:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0007_delete_drink_alter_loanfund_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanfund',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='loanfund',
            name='loan_duration',
            field=models.IntegerField(default=12, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='loanfund',
            name='max_loan_amount',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='loanfund',
            name='min_loan_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
